<a href="https://colab.research.google.com/github/institutohumai/cursos-python/blob/master/AnalisisDeDatos/1_Indexing/ejercicio/ejercicio.ipynb"> <img src='https://colab.research.google.com/assets/colab-badge.svg' /> </a>
<div align="center"> Recordá abrir en una nueva pestaña </div>


Para este ejercicio vamos a importar un conjunto de datos con el listado de colegios públicos de Bogotá del año 2016

# Ejercicio I: base de Colegios de Bogotá.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_colegios = pd.read_csv('https://www.datos.gov.co/api/views/qijw-htwa/rows.csv?accessType=DOWNLOAD')

¿Cuáles son las columnas? ¿Cuántas filas tiene?

In [3]:
print(f"Columnas {df_colegios.columns}")

print(f"Filas totales: {df_colegios.shape[0]}")

Columnas Index(['año', 'secretaria', 'nombreestablecimiento', 'zona', 'direccion',
       'telefono', 'nombre_Rector', 'tipo_Establecimiento', 'etnias', 'sector',
       'genero', 'niveles', 'jornadas', 'caracter', 'especialidad', 'grados',
       'modelos_Educativos', 'capacidades_Excepcionales', 'discapacidades',
       'idiomas', 'numero_de_Sedes', 'estado', 'prestador_de_Servicio',
       'propiedad_Planta_Fisica', 'resguardo', 'matricula_Contratada',
       'calendario', 'internado', 'estrato_Socio_Economico',
       'correo_Electronico'],
      dtype='object')
Filas totales: 2404

Seleccionen los colegios donde la propiedad de la planta física sea de una persona natural o comunidad religiosa.

In [4]:
df_colegios['propiedad_Planta_Fisica'].value_counts()

propiedad_Planta_Fisica
PERSONA NATURAL              1727
OFICIAL                       405
COMUNIDAD RELIGIOSA           151
FUNDACION O CORPORACIONES      46
FEDERACIONES                   17
REGIMEN ESPECIAL               16
COOPERATIVO                    14
COMUNIDAD                      13
CAJA DE COMPENSACIÓN            9
SOCIEDAD                        6
Name: count, dtype: int64

In [5]:
df_1 = df_colegios.query("propiedad_Planta_Fisica == 'PERSONA NATURAL' | propiedad_Planta_Fisica == 'COMUNIDAD RELIGIOSA' ")
df_1.tail()

,año,secretaria,nombreestablecimiento,zona,direccion,telefono,nombre_Rector,tipo_Establecimiento,etnias,sector,...,numero_de_Sedes,estado,prestador_de_Servicio,propiedad_Planta_Fisica,resguardo,matricula_Contratada,calendario,internado,estrato_Socio_Economico,correo_Electronico
2399,2016,BOGOTA,COL LOS ANGELES DE HELVETIA ...,URBANA,KR 42 22 04,2699000,TATIANA GARNICA,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2400,2016,BOGOTA,INST MODERNO EL LIBANO,URBANA,KR 89 B 47 A 02 SUR,4524437,MYRIAM MERCEDES FIGUEROA ENRIQUEZ,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2401,2016,BOGOTA,LIC INF EL MUNDO DEL NIÑO FELIZ ...,URBANA,CLL. 32 NO.118-26,2989793,ELIANA SANABRIA AGUILAR,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN
2402,2016,BOGOTA,LIC PSICOPEDAG ENGATIVA ...,URBANA,KR 125 61 32,4336212,PILAR PALACIOS DE LEON,INSTITUCION EDUCATIVA,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,SI,A,NaN,NaN,NaN
2403,2016,BOGOTA,COL UNID RESIDENCIAL COLSEGUROS ...,URBANA,KR 30 22 A 08 IN 12 TO 2,2698471 / 2685245 / 2446243 ...,MARIA ELVINIA GARCIA CORTES,CENTRO EDUCATIVO,NaN,NaN,...,1,NaN,PERSONA NATURAL,PERSONA NATURAL,NO APLICA,NO,A,NaN,NaN,NaN

¿Hay alguno de estos colegios que sea para capacidades excepcionales?

In [6]:
df_1[df_1["capacidades_Excepcionales"] == "CAPACIDADES EXCEPCIONALES"]["nombreestablecimiento"]
# df_colegios[df_colegios["capacidades_Excepcionales"]  == "CAPACIDADES EXCEPCIONALES"]

537     INST DE PEDAG AUTOACTIVA DE GRUPOS (IPAG)     ...
542     COL JONATHAN SWIFT                            ...
1364    COL CAMPESTRE MAXIMINO POITIERS               ...
1541    LIC VAL (VIDA-AMOR-LUZ)                       ...
1915    LIC ECOLOGICO DEL NORTE                       ...
Name: nombreestablecimiento, dtype: object

In [7]:
# Otra opcion
mascara3_1 = df_colegios['capacidades_Excepcionales'].notna()
mascara3_2 = ~df_colegios['capacidades_Excepcionales'].isna()
# Revisar si las dos mascaras son iguales
print(mascara3_1.shape[0])
print(sum(mascara3_1 == mascara3_2) == mascara3_1.shape[0])
df_colegios[mascara3_1][['nombreestablecimiento', 'capacidades_Excepcionales']]

2404
True

,nombreestablecimiento,capacidades_Excepcionales
491,COLEGIO COLSUBSIDIO CIUDADELA,TALENTO SUBJETIVO/ARTÍSTICO
537,INST DE PEDAG AUTOACTIVA DE GRUPOS (IPAG) ...,CAPACIDADES EXCEPCIONALES
542,COL JONATHAN SWIFT ...,CAPACIDADES EXCEPCIONALES
914,COLEGIO MORISCO (IED),"TALENTO CIENTIFICO,TALENTO TECNOLOGICO,TALENTO..."
985,GIMNASIO CAMPESTRE STEPHEN HAWKING,TALENTO SUBJETIVO/ARTÍSTICO
1097,GIMN TUNDAMA ...,CAPACIDADES EXCEPCIONALES
1169,COL CALATRAVA,TALENTO CIENTIFICO
1364,COL CAMPESTRE MAXIMINO POITIERS ...,CAPACIDADES EXCEPCIONALES
1541,LIC VAL (VIDA-AMOR-LUZ) ...,CAPACIDADES EXCEPCIONALES
1915,LIC ECOLOGICO DEL NORTE ...,CAPACIDADES EXCEPCIONALES

In [8]:
df_colegios[mascara3_1]['capacidades_Excepcionales'].value_counts()

capacidades_Excepcionales
CAPACIDADES EXCEPCIONALES                                             6
TALENTO SUBJETIVO/ARTÍSTICO                                           2
TALENTO CIENTIFICO,TALENTO TECNOLOGICO,TALENTO SUBJETIVO/ARTÍSTICO    1
TALENTO CIENTIFICO                                                    1
Name: count, dtype: int64

¿Cuáles son los colegios que ofrecen todos los niveles educativos? ¿Qué idiomas ofrecen?

In [9]:
df_colegios["niveles"].value_counts()
df_colegios.query("niveles == 'PREESCOLAR,MEDIA,BÁSICA SECUNDARIA,BÁSICA PRIMARIA,PRIMERA INFANCIA' ")[["nombreestablecimiento", "idiomas"]]

                                  nombreestablecimiento idiomas
251                       COLEGIO NUEVO HORIZONTE (IED)     NaN
464                    COLEGIO TOMAS CARRASQUILLA (IED)     NaN
810   COL SAN PATRICIO                              ...  INGLÉS
1176         COLOMBO BRITANICO - BILINGÜE INTERNACIONAL  INGLÉS
1222                            INSTITUTO JUAN PABLO II     NaN

# Ejercicio II: PyEPH

### PyEPH

La librería Pyeph tiene como objetivo facilitar el procesamiento en Python de las Encuesta Permanente de Hogares (eph) publicadas por INDEC de forma periódica. Está pensada como un espacio donde se nuclean y centralizan los cálculos vinculados a las mismas para posteriormente ser utilizadas en investigaciones, artículos, publicaciones, etc. Es una librería que hace principal hincapié en la transparencia metodológica utilizando licencias de código abierto y que promueve la colaboración de las comunidades de cientístas de datos, sociales, investigadorxs, desarrolladorxs, periodistas y demás curiosxs.

https://github.com/institutohumai/pyeph

Para entender qué representan las columnas ver documentación:


https://www.indec.gob.ar/ftp/cuadros/menusuperior/eph/EPH_diseno_reg_t414.pdf

In [10]:
# Instalamos la librería.

!pip install pyeph

Collecting pyeph
  Downloading pyeph-1.6.1-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: ipykernel<7.0.0,>=6.13.0 in /usr/local/lib/python3.12/dist-packages (from pyeph) (6.17.1)
Requirement already satisfied: openpyxl<4.0.0,>=3.0.10 in /usr/local/lib/python3.12/dist-packages (from pyeph) (3.1.5)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pyeph) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from pyeph) (2.32.4)
Requirement already satisfied: tqdm<5.0.0,>=4.66.0 in /usr/local/lib/python3.12/dist-packages (from pyeph) (4.67.3)
Requirement already satisfied: xlrd<3.0.0,>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from pyeph) (2.0.2)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (6.5.1)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel<7.0.0,>=6.13.0->pyeph) (5.7.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl<4.0.0,>=3.0.10->pyeph) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->pyeph) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->pyeph) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->pyeph) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->pyeph) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->pyeph) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->pyeph) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->pyeph) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->pyeph) (2026.1.4)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (4.9.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.13.0->pyeph) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.13.0->pyeph) (5.9.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->pyeph) (1.17.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.8.5)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.13.0->pyeph) (4.5.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel<7.0.0,>=6.13.0->pyeph) (0.5.3)
Downloading pyeph-1.6.1-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.3/66.3 kB 2.5 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.3 MB/s eta 0:00:00
Installing collected packages: jedi, pyeph
Successfully installed jedi-0.19.2 pyeph-1.6.1

In [11]:
import pyeph

In [12]:
# Ejemplo: traemos el 2do trimestre del 2021
eph = pyeph.get(data="eph", year=2021, period=2, base_type='individual') # EPH individual

Descargando base_individual_2021T2.zip: 100%|█| 2.09M/2.09M [00:00<00:00, 36.7MB

In [13]:
eph.columns

Index(['CODUSU', 'ANO4', 'TRIMESTRE', 'NRO_HOGAR', 'COMPONENTE', 'H15',
       'REGION', 'MAS_500', 'AGLOMERADO', 'PONDERA',
       ...
       'PDECIFR', 'ADECIFR', 'IPCF', 'DECCFR', 'IDECCFR', 'RDECCFR', 'GDECCFR',
       'PDECCFR', 'ADECCFR', 'PONDIH'],
      dtype='object', length=177)

**Primer paso.** Crear una variable llamada eph_2 que contenga las siguientes columnas para realizar el siguiente análisis:

Edad (**CH_06**), Sexo (**CH_04**), Ingreso de la ocupación principal (**P21**), Categoría ocupacional (**CAT_OCUP**), Condición de actividad (ESTADO), Ponderación (**PONDERA**)

Referencias:

Sexo:
*   01 = Varón
*   02 = Mujer

Categoría ocupacional (para ocupados y desocupados con
ocupación anterior):
*   1 = Patrón
*   2 = Cuenta propia
*   3 = Obrero o empleado
*   4 = Trabajador familiar sin remuneración
*   9 = Ns/Nr

Estado - Condición de actividad:
*   0 = Entrevista individual no realizada
*   1 = Ocupado
*   2 = Descoupado
*   3 = Inactivo
*   4 = menor de 10 años

In [14]:
#Filtramos por columnas
eph_2=eph[["CH06", "CH04", "P21", "CAT_OCUP", "ESTADO", "PONDERA"]]

In [15]:
#Renombramos columnas
eph_2.columns=["edad", "sexo", "ingreso", "cat_ocup", "estado", "pondera"]

La columna **pondera** representa un estimado poblacional de las personas que representa cada fila. Por lo tanto, para cada cálculo es necesario operar con esa columna. Por ejemplo, la fila 0 representa a 214 personas de 58 años de sexo masculino, que tienen $50.000 de ingreso de la ocupación principal, su categoría es cuentapropista y pertenecen al segmento de ocupados.

In [16]:
eph_2.head()

   edad  sexo  ingreso  cat_ocup  estado  pondera
0    58     1    50000         2       1      214
1    24     1        0         3       2      214
2    51     2        0         4       1      192
3    27     1     4000         2       1      192
4    18     1        0         0       3      192

a) Traer un dataframe que filtre solo a las personas que tengan 21 años o menos.

In [17]:
eph_2.query("edad <= 21").sample(10)

       edad  sexo  ingreso  cat_ocup  estado  pondera
35449    17     1        0         0       3      347
46642     8     2        0         0       4      312
5761      8     1        0         0       4     3647
7227     15     2        0         0       3      231
23186    14     1        0         0       3      202
8157      7     1        0         0       4      128
8043     10     2        0         0       3      161
39942     9     2        0         0       4      483
2426      7     1        0         0       4      821
34245     2     1        0         0       4      324

b) Traer un dataframe que filtre a las personas desocupadas de más de 40 años.

In [18]:
eph_2.query("edad == 40 & estado == 2").sample(10)

       edad  sexo  ingreso  cat_ocup  estado  pondera
29535    40     2        0         3       2      257
40046    40     2        0         3       2      544
41382    40     2        0         2       2      451
25201    40     2        0         3       2      318
39804    40     1        0         2       2      102
44511    40     2        0         0       2      800
25605    40     1        0         2       2      241
29569    40     1        0         2       2      173
24335    40     1        0         3       2       55
43174    40     2        0         3       2      409

c) ¿Cuántas mujeres hay en la base de datos? ¿Y hombres?

In [19]:
eph_2["sexo"].value_counts()

sexo
2    24483
1    22602
Name: count, dtype: int64

In [20]:
eph_mujeres = eph_2[eph_2['sexo'] == 2]
eph_varones = eph_2[eph_2['sexo'] == 1]

print('El total de mujeres es:', eph_mujeres['pondera'].sum())
print('El total de varones es:', eph_varones['pondera'].sum())

El total de mujeres es: 14833824
El total de varones es: 14038615

d) ¿Cuál era la tasa de desocupación en el período seleccionado para las mujeres? ¿Era más alta o más baja que la de los hombres? (Extra: pensar el resultado usando una función)

Nota: la tasa se calcula como Desocupados / (Ocupados + Desocupados)

In [21]:
"""
Estado - Condición de actividad:
0 = Entrevista individual no realizada
1 = Ocupado
2 = Descoupado
3 = Inactivo
4 = menor de 10 años
"""

mujeres_desocupadas = eph_2[eph_2["sexo"] == 2].query("estado == 2")["pondera"].sum()
mujeres_ocupadas = eph_2[eph_2["sexo"] == 2].query("estado == 1")["pondera"].sum()
tasa_deso_mujeres = mujeres_desocupadas / (mujeres_desocupadas + mujeres_ocupadas)


hombres_desocupados = eph_2[eph_2["sexo"] == 1].query("estado == 2")["pondera"].sum()
hombres_ocupados = eph_2[eph_2["sexo"] == 1].query("estado == 1")["pondera"].sum()
tasa_deso_hombres = hombres_desocupados / (hombres_desocupados + hombres_ocupados)

print(f"Tasa de desocupación en mujeres {tasa_deso_mujeres*100}%")
print(f"Tasa de desocupación en hombres {tasa_deso_hombres*100}%")

Tasa de desocupación en mujeres 10.38734531064664%
Tasa de desocupación en hombres 9.005636202663633%

In [22]:
def get_tasa_desocupacion(sexo:int) -> float:
  desocupacion = eph_2[eph_2["sexo"] == sexo].query("estado == 2")["pondera"].sum()
  ocupacion = eph_2[eph_2["sexo"] == sexo].query("estado == 1")["pondera"].sum()

  return round((desocupacion / (desocupacion + ocupacion))*100, 3)

tasa_mujer = get_tasa_desocupacion(2)
tasa_varon = get_tasa_desocupacion(1)

print(f"Tasa de desocupación en mujeres {tasa_mujer}%")
print(f"Tasa de desocupación en hombres {tasa_varon}%")

if tasa_mujer > tasa_varon:
  print('La tasa de desocupacion es mas alta en: Mujeres')
else:
  print('La tasa de desocupacion es mas alta en: Varones')

Tasa de desocupación en mujeres 10.387%
Tasa de desocupación en hombres 9.006%
La tasa de desocupacion es mas alta en: Mujeres

Otro Ejemplo de resolución

In [25]:
# Estado 1 (Ocupado) y 2 (Desocupado). Ignoramos inactivos (3) y menores (4).
df_pea = eph_2[eph_2['estado'].isin([1, 2])]
df_pea['estado'].value_counts()

estado
1    19408
2     1737
Name: count, dtype: int64

In [34]:
# Agrupamos por sexo y estado, y sumamos la ponderación
# sin unstruck
agrupado = df_pea.groupby(['sexo', 'estado'])['pondera'].sum()
print(agrupado)
# utilizando unstruck
#remodela un DataFrame moviendo el nivel más interno de un índice
# jerárquico (filas) hacia el eje de las columnas, convirtiendo un formato "largo" o "apilado" en uno "ancho"
agrupado = df_pea.groupby(['sexo', 'estado'])['pondera'].sum().unstack()
agrupado

sexo  estado
1     1         6864532
      2          679377
2     1         5116948
      2          593125
Name: pondera, dtype: int64

estado        1       2
sexo
1       6864532  679377
2       5116948  593125

In [35]:
# Renombramos columnas para que sea legible (1=Ocupado, 2=Desocupado)
agrupado.columns = ['ocupados', 'desocupados']
agrupado

      ocupados  desocupados
sexo
1      6864532       679377
2      5116948       593125

In [36]:
# Calculamos la tasa vectorizada (para todas las filas a la vez)
agrupado['tasa_desocupacion'] = (agrupado['desocupados'] / (agrupado['ocupados'] + agrupado['desocupados'])) * 100

print(agrupado['tasa_desocupacion'].round(3))

# Lógica para imprimir quién es mayor (automática)
if agrupado.loc[2, 'tasa_desocupacion'] > agrupado.loc[1, 'tasa_desocupacion']:
    print("La tasa es mayor en Mujeres")
else:
    print("La tasa es mayor en Varones")

sexo
1     9.006
2    10.387
Name: tasa_desocupacion, dtype: float64
La tasa es mayor en Mujeres

In [37]:
agrupado

      ocupados  desocupados  tasa_desocupacion
sexo
1      6864532       679377           9.005636
2      5116948       593125          10.387345